COPTS=-ggdb3 -DMAX_KEYS_GEN=10

CUNITINC=/usr/local/include/
PKCS11INC=./pkcs11-include/

CUNITLIB=/usr/local/lib/libcunit.a
# PKCS11LIB=/usr/lib/libepsng_p11.so
# PKCS11LIB=/usr/local/lib/libsofthsm.so

INCS=-I $(CUNITINC) -I $(PKCS11INC)
# LIBS=$(CUNITLIB) $(PKCS11LIB) -lbotan
LIBS=$(CUNITLIB) -ldl -lm

#
# During development of this test, it takes too long to run tests at full
# length.  ONLY for the purpose of developing hsmbully has the quickndirty
# check been included.
#
all: thorough-hsmbully quickndirty-hsmbully

thorough-hsmbully: hsmbully.c
	gcc $(COPTS) $(INCS) -o thorough-hsmbully hsmbully.c $(LIBS)

quickndirty-hsmbully: hsmbully.c
	gcc $(COPTS) -DQUICK_N_DIRTY $(INCS) -o quickndirty-hsmbully hsmbully.c $(LIBS)

hsmbully.c: Makefile
	touch hsmbully.c

clean:
	rm -f *.o thorough-hsmbully quickndirty-hsmbully

