#!/bin/sh
#
# $Id$
#
# This script will set up a quick test environment for OpenDNSSEC

SOFTHSM_CONF=/etc/softhsm.conf
SOFTHSM_SLOT0=/var/opendnssec/softhsm0.db
OPENDNSSEC_CONF=/etc/opendnssec/conf.xml
KASP_DB=/var/opendnssec/kasp.db


if [ ! -f ${SOFTHSM_CONF} ]; then
	echo "Creating template softHSM configuration file as ${SOFTHSM_CONF}"
	cat <<EOF >${SOFTHSM_CONF}
# softhsm.conf (autogenerated by $0)
0:${SOFTHSM_SLOT0}
EOF
else
	echo "${SOFTHSM_CONF} already exists - will not overwrite"
	exit 1
fi

if [ ! -f ${SOFTHSM_SLOT0} ]; then
	echo "Initializing softHSM token (slot 0)"
	softhsm --init-token --slot 0 --label "OpenDNSSEC" \
		--pin 1234 --so-pin 1234567890
else
	echo "${SOFTHSM_SLOT0} already exists - will not overwrite"
	exit 1
fi

if [ ! -f ${OPENDNSSEC_CONF} ]; then
	echo "OpenDNSSEC configuration not found - not installed?"
	exit 1
fi

if [ -f ${KASP_DB} ]; then
	echo "Existing KASP database found - will not overwrite"
	exit 1
else
	echo "Setting up KASP database"
	ksmutil setup
fi

