# Tested locally with https://github.com/nektos/act
# Command: act workflow_dispatch
# See also: .actrc
# If using a Docker volume with act: docker run --rm -it -v ods-root:/tmp/root ubuntu:latest /bin/bash -c 'rm /tmp/root/var/run/opendnssec/*'
name: CI

on:
  push:
  workflow_dispatch:
    inputs:
      run-in-parallel:
        description: 'True to run tests in parallel (default), false to run tests sequentially'
        default: false
        type: boolean

defaults:
  run:
    # see: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell
    shell: bash --noprofile --norc -eo pipefail -x {0}

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  build:
    runs-on: ods-build-job # ubuntu-latest

    outputs:
      tests: ${{ steps.matrix.outputs.tests }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: workspace

      - name: Install pre-requisites
        run: |
          sudo apt-get update

          # default-jre is needed for relaxng XML schema support
          # libcunit1-dev is needed for running unit tests
          # libldns-dev is needed by OpenDNSSEC
          # psmisc is needed by the test scripts to run killall
          # sqlite3 is needed when using SQLite3 as the database for ODS

          sudo apt-get install \
              -y \
              --no-install-recommends \
              --no-install-suggests \
            default-jre   \
            libcunit1-dev \
            libldns-dev   \
            psmisc        \
            sqlite3

      - name: Setup environment for subsequent steps
        working-directory: workspace
        run: |
          WORKSPACE=$(pwd)
          INSTALL_ROOT=$HOME/ROOT
          PATH=$PATH:${INSTALL_ROOT}/bin/

          mkdir -p ${INSTALL_ROOT}

          echo "${INSTALL_ROOT}/bin/" >> "$GITHUB_PATH"
          echo "WORKSPACE=${WORKSPACE}" >> "$GITHUB_ENV"
          echo "INSTALL_ROOT=${INSTALL_ROOT}" >> "$GITHUB_ENV"

          sudo chown -R runner: ${INSTALL_ROOT}

#      - name: Build and install SoftHSMv2
#        working-directory: workspace
#        run: |
#          if [ -f ${INSTALL_ROOT}/bin/softhsm2-util ]; then
#            exit 0
#          fi
#
#          wget https://dist.opendnssec.org/source/softhsm-2.6.1.tar.gz
#          tar xzf softhsm-2.6.1.tar.gz
#          cd softhsm-2.6.1
#          ./configure \
#            --prefix=${INSTALL_ROOT} \
#            --sbindir=${INSTALL_ROOT}/bin \
#            --mandir=${INSTALL_ROOT}/man \
#            --disable-non-paged-memory \
#            --with-migrate \
#            --disable-p11-kit \
#            --with-crypto-backend=openssl \
#            --disable-ecc \
#            --disable-gost
#          make
#          make install
#
#          touch ${INSTALL_ROOT}/.softhsm2.ok

      - name: Build and install OpenDNSSEC
        working-directory: workspace
        run: |
          ls -la ${INSTALL_ROOT}
          testing/build-opendnssec.sh

      - name: Tar ROOT
        working-directory: workspace
        run: |
          tar -zcvf ROOT.tgz build -C $HOME ROOT

      - name: Upload ROOT tarball
        uses: actions/upload-artifact@v4
        with:
          name: root
          path: workspace/ROOT.tgz
          if-no-files-found: error
          retention-days: 1

      - name: Create test matrix
        id: matrix
        working-directory: workspace
        run: |
          if [[ "${{ inputs.run-in-parallel }}" == "false" ]]; then
            # MATRIX_JSON='tests=["test-cases.d"]'
            # MATRIX_JSON='tests=["test-cases.d/signer.adapters.input_basic"]'
            MATRIX_JSON='tests=["test-cases.d/enforcer.keys.backup"]'
          else
            MATRIX_JSON='tests='
            SEP_CHAR='['
            cd testing
            for TEST_DIR in test-cases.d/*; do
              echo "${TEST_DIR}"
              if [ ! -f "${TEST_DIR}/OFF" ]; then
                # TEST_NAME=$(basename $TEST_DIR)
                MATRIX_JSON="${MATRIX_JSON}""${SEP_CHAR}"'"'$TEST_DIR'"'
                SEP_CHAR=','
              fi
            done
            MATRIX_JSON="${MATRIX_JSON}]"
          fi

          echo "${MATRIX_JSON}" >> "${GITHUB_OUTPUT}"

  test:
    runs-on: ods-test-job # ubuntu-latest
    needs: build
    strategy:
      matrix:
        test: ${{ fromJSON(needs.build.outputs.tests) }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: workspace

      - name: Download ROOT tarball
        uses: actions/download-artifact@v4
        with:
          name: root

      - name: Unpack ROOT tarball
        run: |
          tar -zxvf ROOT.tgz -C $HOME

      - name: Install pre-requisites
        run: |
          sudo apt-get update

          # bind9 is needed for named used by test-cases.d/signer.adapters.bind_stress_test
          # default-jre is needed for relaxng XML schema support
          # ldnsutils is needed for ldns-testns used by test-cases.d/signer.adapters.input_basic
          #                     for ldns-notify used by test-cases.d/signer.adapters.input_ixfr_notimpl
          # libcunit1-dev is needed for running unit tests
          # libldns-dev is needed by OpenDNSSEC
          # libxml2-utils is needed for xmllint used by functions-opendnssec.sh used by test-cases.d/enforcer.ods-enforcer.zones_and_zonelist
          # perl is used by test-cases.d/signer.adapters.bind_stress_test
          # psmisc is needed by the test scripts to run killall
          # sqlite3 is needed when using SQLite3 as the database for ODS
          # xsltproc is needed for xsltproc used by functions-opendnssec.sh used by test-cases.d/enforcer.ods-enforcer.zones_and_zonelist

          sudo apt-get install \
              -y \
              --no-install-recommends \
              --no-install-suggests \
            bind9         \
            default-jre   \
            libcunit1-dev \
            libldns-dev   \
            libxml2-utils \
            perl          \
            psmisc        \
            sqlite3       \
            tshark        \
            xsltproc

          # # Install ldns-testns
          # sudo apt-get install -y build-essential git libtool libssl-dev
          # git clone --depth 1 https://github.com/NLnetLabs/ldns.git -b master
          # cd ldns
          # git submodule update --init
          # libtoolize -ci
          # autoreconf -fi
          # ./configure --with-examples --with-drill
          # make
          # make install

          # Try dnst testns instead as ldns-testns is core dumping...
          sudo apt-get install -y build-essential curl libssl-dev pkg-config
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sudo sh -s -- -y --profile minimal --default-toolchain stable
          . "$HOME/.cargo/env"
          cargo install --git https://github.com/NLnetLabs/dnst --branch ldns-testns
          P=$HOME/.cargo/bin/dnst
          [ -h /usr/bin/ldns-testns ] || sudo ln -s $P /usr/bin/ldns-testns
          [ -h /usr/bin/ldns-notify ] || sudo ln -s $P /usr/bin/ldns-notify

      - name: Install and start the syslog daemon
        run: |
          sudo apt-get install \
            -y \
            --no-install-recommends \
            --no-install-suggests \
            syslog-ng
  
          # Remove PIDs from syslog lines so that ODS test suite syslog line matching works.
          # See: https://serverfault.com/questions/981150/disable-process-id-showing-in-syslog-ng-logs
          grep -F 'file("/var/log/syslog")' /etc/syslog-ng/syslog-ng.conf && \
            sudo sed -i -e 's|file("/var/log/syslog")|file("/var/log/syslog" template("$DATE $HOST $PROGRAM: $MESSAGE\\n"))|' /etc/syslog-ng/syslog-ng.conf
  
          sudo syslog-ng
  
          sleep 1s
  
          # sudo touch /var/log/syslog
          sudo chmod a+rw /var/log/syslog

      - name: Setup environment for subsequent steps
        run: |
          WORKSPACE=$(pwd)
          INSTALL_ROOT=$HOME/ROOT
          PATH=$PATH:${INSTALL_ROOT}/bin/

          echo "${INSTALL_ROOT}/bin/" >> "$GITHUB_PATH"
          echo "WORKSPACE=${WORKSPACE}" >> "$GITHUB_ENV"
          echo "INSTALL_ROOT=${INSTALL_ROOT}" >> "$GITHUB_ENV"

      - name: Prepare OpenDNSSEC test suite environment
        run: |
          cd $HOME/build
          echo "SVN_REVISION=1" >> "$GITHUB_ENV"
          echo "" > $INSTALL_ROOT/.botan.ok
          echo "1" > $INSTALL_ROOT/.botan.build
          echo "" > $INSTALL_ROOT/.softhsm2.ok
          echo "1-openssl:1" > $INSTALL_ROOT/.softhsm2.build
          echo "" > $INSTALL_ROOT/.opendnssec.ok
          echo "1" > $INSTALL_ROOT/.opendnssec.build
          cat > $INSTALL_ROOT/etc/softhsm2.conf.build <<-END
          directories.tokendir = $INSTALL_ROOT/var/lib/softhsm/tokens/
          objectstore.backend = file
          log.level = INFO
          END
          for f in conf/{addns,conf,kasp,zonelist}.xml
          do
            cp $f $INSTALL_ROOT/etc/opendnssec/`basename $f`.build
          done

      - name: Run test ${{ matrix.test }}
        id: run_test
        working-directory: workspace
        run: |
          export PATH=${INSTALL_ROOT}/sbin:$PATH

          # When using nektos/act to run locally and using a ROOT volume to
          # cache built artifacts, state from previous runs can get left
          # behind so cleanup a bit first.
          pushd ${INSTALL_ROOT}
          find . -name \*.pid -delete || true
          find . -name \*.sock -delete || true
          killall -9 ods-signerd || true
          killall -9 ods-enforcerd || true
          find . -name \*core -delete || true
          rm -rf var/lib/softhsm/tokens/* || true
          rm -f $root/var/opendnssec/enforcer/zones.xml || true
          rm -f $root/var/opendnssec/signed/* || true
          rm -f $root/var/opendnssec/signer/* || true
          rm -f $root/var/opendnssec/signconf/* || true
          rm -f $root/var/opendnssec/kasp.db || true
          popd

          cd testing
          if [[ "${{ matrix.test }}" == "test-cases.d" ]]; then
            ./test-opendnssec.sh
          else
            cd ${{ matrix.test }}
            sudo tshark -i any -d udp.port==15353,dns -d udp.port==15354,dns port 15353 or port 15354 &> _tshark.log &
            ../../test-this.sh || echo "test_result=FAILED" >> "${GITHUB_OUTPUT}"
          fi

      - name: Dump diagnostics on single test failure
        if: steps.run_test.outputs.test_result == 'FAILED'
        working-directory: workspace
        run: |
          cd testing/${{ matrix.test }}

          echo "::notice::Listing test directory contents"
          ls -la

          echo "::notice::Dumping left over _log files"
          for F in $(ls -1 _*); do
            echo "::notice::Dumping $F"
            cat $F
          done

          echo "::notice::Listing $INSTALL_ROOT directory contents"
          ls -lR $INSTALL_ROOT

          echo "::notice::Dumping running processes tree"
          pstree -n -p

          exit 1
